{% set name = "EasyOCR" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JaidedAI/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0ed5af2b739ce2303c5173d520b631df311d54a9aa58a80e09fe33d44c0a8115

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vvv
  entry_points:
    - easyocr= easyocr.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - numpy   1.19  # [py<310]
    - numpy   1.21  # [py>=310]
  run:
    - ninja
    - {{ pin_compatible('numpy') }}
    - pillow
    - py-opencv
    - pyclipper
    - python
    - python-bidi
    - pyyaml
    - scikit-image
    - scipy
    - shapely
    - pytorch
    - torchvision >=0.5

test:
  imports:
    - easyocr
  requires:
    - pip
    - ninja
    # 2022/9/29: Fix for scipy 1.7.3:
    - numpy <1.23
  commands:
    # 2022/9/29: To pass pip check opencv-python-headless<=4.5.4.60 and ninja are needed.
    # It's weird that ninja is needed because it's already in run and test/requires.
    # opencv-python-headless is needed only for tests, in run is used py-opencv.
    - pip install ninja "opencv-python-headless<=4.5.4.60"
    - pip check
    - easyocr --help

about:
  home: https://www.jaided.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  license_file:
  summary: End-to-End Multi-Lingual Optical Character Recognition (OCR) Solution
  description: |
    Ready-to-use OCR with 80+ supported languages and all popular writing
    scripts including: Latin, Chinese, Arabic, Devanagari, Cyrillic, etc.

  doc_url: https://github.com/JaidedAI/EasyOCR/blob/master/README.md
  dev_url: https://github.com/jaidedai/easyocr

extra:
  recipe-maintainers:
    - skupr-anaconda
