{% set name = "EasyOCR" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JaidedAI/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6f26c99ecfd3f715932e470836c2dd80fb55509df18955ff863f0212d19c23ad

build:
  number: 0
  # torchvision currently isn't available on s390x and ppc64le.
  skip: True  # [s390x or ppc64le]
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - easyocr= easyocr.cli:main

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - pytorch
    - torchvision >=0.5
    - py-opencv >=4.6.0
    - scipy
    - numpy
    - pillow
    - scikit-image
    - python-bidi
    - pyyaml
    - shapely
    - pyclipper
    - ninja

test:
  # Imports in run_test.py
  #imports:
  #  - easyocr
  requires:
    - pip
  files:
    - english.png

about:
  home: https://www.jaided.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: End-to-End Multi-Lingual Optical Character Recognition (OCR) Solution
  description: |
    Ready-to-use OCR with 80+ supported languages and all popular writing
    scripts including: Latin, Chinese, Arabic, Devanagari, Cyrillic, etc.

  doc_url: https://github.com/JaidedAI/EasyOCR/blob/master/README.md
  dev_url: https://github.com/JaidedAI/EasyOCR

extra:
  recipe-maintainers:
    - skupr-anaconda
  skip-lints:
    - missing_pip_check
    - has_run_test_and_commands
    - build_tools_must_be_in_build
